print "Conversion\tMeaning\n"
print "'d'\t\tSigned Integer decimal"
print "'i'\t\tSigned Integer decimal"
print "'o'\t\tSigned octal value"
print "'u'\t\tObsolete type-It is identical to 'd'"
print "'x'\t\tSigned hexadecimal-lowercase"
print "'X'\t\tSigned hexadecimal-uppercase"
print "'e'\t\tFloating point exponential format-lowercase"
print "'E'\t\tFloating point exponential formal-uppercase"
print "'f'\t\tFloating point decimal format"
print "'F'\t\tFloating point decimal format"
print "'g'\t\tFloating point format.\n\t\tUses lowercase exponential format\n\t\tif exponent is less than -4 or\n\t\tnot less than precision, decimal format otherwise"
print "'G'\t\tFloating point format.\n\t\tUses lowercase exponential format\n\t\tif exponent is less than -4 or\n\t\tnot less than precision, decimal format otherwise"
print "'c'\t\tSingle character (accepts interger or single character string)"
print "'r'\t\tString (converts any Python object using repr())"
print "'s'\t\tString (converts any Python object using str())"
print "'%'\t\tNo argument is converted, results in a '%' character in the result"
